import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, BrainCircuit, LayoutDashboard, FileText, Calendar } from 'lucide-react';
import { Button, Card, StatusBadge } from '../components/ui';
import { store } from '../services/store';
import { explainMedicalRecord } from '../services/geminiService';
import { MedicalRecord } from '../types';
import { MarkdownRenderer } from '../components/MarkdownRenderer';

export const AISummaryPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [record, setRecord] = useState<MedicalRecord | null>(null);
  const [explanation, setExplanation] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (id) {
      const r = store.getRecordById(id);
      if (r) {
        setRecord(r);
        // If we already have a structured AI summary from upload, use it.
        if (r.aiSummary && r.aiSummary.length > 50) {
            setExplanation(r.aiSummary);
            setLoading(false);
        } else {
            // Fallback for older records
            explainMedicalRecord(
                typeof r.content === 'string' ? r.content : JSON.stringify(r.content), 
                r.type
            ).then(text => {
                setExplanation(text);
                setLoading(false);
            });
        }
      } else {
        navigate('/patient/dashboard');
      }
    }
  }, [id, navigate]);

  if (!record) return null;

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Navigation Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <Button variant="ghost" onClick={() => navigate(-1)} className="self-start gap-2 text-slate-600">
          <ArrowLeft className="h-4 w-4" /> Back
        </Button>
        <div className="flex gap-2">
            <Button variant="outline" onClick={() => navigate('/patient/dashboard')} className="gap-2">
                <LayoutDashboard className="h-4 w-4" /> Back to Dashboard
            </Button>
        </div>
      </div>

      <div className="grid md:grid-cols-3 gap-6">
        {/* Left Col: Original Record Info */}
        <div className="md:col-span-1 space-y-6 order-2 md:order-1">
             <Card className="p-5">
                <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-4">Source Record</h3>
                <div className="mb-4">
                    <h2 className="font-bold text-slate-900 leading-tight">{record.title}</h2>
                    <div className="flex items-center gap-2 mt-2 text-sm text-slate-500">
                        <Calendar className="h-4 w-4" />
                        {new Date(record.date).toLocaleDateString()}
                    </div>
                </div>
                <StatusBadge verified={record.verified} />
                <div className="mt-6 pt-6 border-t border-slate-100">
                     <p className="text-xs text-slate-500 mb-2">Doctor / Provider</p>
                     <p className="font-medium text-slate-900">{record.doctorName || 'Unknown'}</p>
                </div>
             </Card>
        </div>

        {/* Right Col: AI Explanation */}
        <div className="md:col-span-2 space-y-6 order-1 md:order-2">
            <Card className="p-0 overflow-hidden border-indigo-100 shadow-md">
                <div className="bg-indigo-50/50 p-6 border-b border-indigo-100">
                    <div className="flex items-center gap-3 mb-2">
                        <div className="p-2 bg-indigo-100 text-indigo-600 rounded-lg">
                            <BrainCircuit className="h-6 w-6" />
                        </div>
                        <h1 className="text-xl font-bold text-indigo-950">AI Health Summary</h1>
                    </div>
                    <p className="text-indigo-900/70 text-sm">
                        Generated by Gemini 2.5 Flash • Medical Assistant
                    </p>
                </div>
                
                <div className="p-6 md:p-8">
                    {loading ? (
                         <div className="space-y-4 animate-pulse">
                            <div className="h-4 bg-indigo-50 rounded w-3/4"></div>
                            <div className="h-4 bg-indigo-50 rounded w-full"></div>
                            <div className="h-4 bg-indigo-50 rounded w-5/6"></div>
                        </div>
                    ) : (
                        <div className="prose prose-indigo max-w-none">
                            <MarkdownRenderer content={explanation} />
                        </div>
                    )}
                </div>
                
                <div className="bg-slate-50 p-4 border-t border-slate-100 text-center text-xs text-slate-400">
                    AI generated content may be inaccurate. Please consult your doctor for medical advice.
                </div>
            </Card>
            
            <div className="bg-white rounded-lg border border-slate-200 p-4">
                 <h4 className="font-medium text-slate-900 mb-2 flex items-center gap-2">
                    <FileText className="h-4 w-4 text-slate-400" />
                    Original Data Snippet
                 </h4>
                 <pre className="text-xs text-slate-500 bg-slate-50 p-2 rounded overflow-x-auto">
                    {typeof record.content === 'string' 
                        ? record.content.slice(0, 300) + (record.content.length > 300 ? '...' : '') 
                        : JSON.stringify(JSON.parse(record.content as any), null, 2)
                    }
                 </pre>
            </div>
        </div>
      </div>
    </div>
  );
};